### ISSUE TITLE
Any plans on offering placeholders?

### ISSUE THREAD

**Issue by EugenMayer** [henry40408/concourse-ssh-resource#47]
Sometimes you need placeholders / parameters in your SSH tasks.

Are you interested in implemented placeholder1, placeholder2, placeholder3 which are then useable in the command, readed from a file ( like an input ) ?

**Comment by henry40408** [comment]
Yes, but can you help me with some examples, scenarios or more details?

**Comment by EugenMayer** [comment]
Sure i come up with something, just wanted to hear if there is a general interest in improving the resource. Let me start the work and i connect back to you ASAP

**Comment by EugenMayer** [comment]
see #48
